version: '3.8'

services:
  n8ntest:
    image: n8nio/n8n:{version}
    container_name: n8ntest
    ports:
      - "15678:5678"
    environment:
      - N8N_DEFAULT_LOCALE=ja
      - N8N_SECURE_COOKIE=false
    volumes: []
    stdin_open: true
    tty: true
    restart: unless-stopped
